[project]
name = "ai-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.9.0",
    "openai>=1.58.1",
    "pydantic>=2.10.3",
    "python-dotenv>=1.0.1",
]
